##########################################################################
# Title:            Sandbox: template role                               #
# Author(s):        Grostim                                              #
# URL:              https://github.com/saltyorg/Saltbox_mod              #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

helloworld_name: helloworld

################################
# Paths
################################

helloworld_paths_folder: "{{ helloworld_name }}"
helloworld_paths_location: "{{ server_appdata_path }}/{{ helloworld_paths_folder }}"
helloworld_paths_folders_list:
  - "{{ helloworld_paths_location }}"

################################
# Web
################################

helloworld_web_subdomain: "{{ helloworld_name }}"
helloworld_web_domain: "{{ user.domain }}"
helloworld_web_port: "80"
helloworld_web_url: "{{ 'https://' + (helloworld_web_subdomain + '.' + helloworld_web_domain
                     if (helloworld_web_subdomain | length > 0)
                     else helloworld_web_domain) }}"

################################
# DNS
################################

helloworld_dns_record: "{{ helloworld_web_subdomain }}"
helloworld_dns_zone: "{{ helloworld_web_domain }}"
helloworld_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

helloworld_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}" # Set to "" if you don't need authelia authentication
helloworld_traefik_middleware_default: "{{ traefik_default_middleware }}"
helloworld_traefik_middleware_custom: ""
helloworld_traefik_certresolver: "{{ traefik_default_certresolver }}"
helloworld_traefik_enabled: true
helloworld_traefik_api_enabled: false
helloworld_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
helloworld_docker_container: "{{ helloworld_name }}"

# Image
helloworld_docker_image_pull: true
helloworld_docker_image_tag: "latest"
helloworld_docker_image: "tutum/hello-world:{{ helloworld_docker_image_tag }}"

# Ports
helloworld_docker_ports_defaults: []
helloworld_docker_ports_custom: []
helloworld_docker_ports: "{{ helloworld_docker_ports_defaults
                             + helloworld_docker_ports_custom }}"

# Envs
helloworld_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
helloworld_docker_envs_custom: {}
helloworld_docker_envs: "{{ helloworld_docker_envs_default
                            | combine(helloworld_docker_envs_custom) }}"

# Commands
helloworld_docker_commands_default: []
helloworld_docker_commands_custom: []
helloworld_docker_commands: "{{ helloworld_docker_commands_default
                                + helloworld_docker_commands_custom }}"

# Volumes
helloworld_docker_volumes_default:
  - "{{ helloworld_paths_location }}:/config"
helloworld_docker_volumes_custom: []
helloworld_docker_volumes: "{{ helloworld_docker_volumes_default
                               + helloworld_docker_volumes_custom
                               + docker_volumes_downloads_common }}"

# Devices
helloworld_docker_devices_default: []
helloworld_docker_devices_custom: []
helloworld_docker_devices: "{{ helloworld_docker_devices_default
                               + helloworld_docker_devices_custom }}"

# Hosts
helloworld_docker_hosts_default: []
helloworld_docker_hosts_custom: []
helloworld_docker_hosts: "{{ docker_hosts_common
                             | combine(helloworld_docker_hosts_default)
                             | combine(helloworld_docker_hosts_custom) }}"

# Labels
helloworld_docker_labels_default: {}
helloworld_docker_labels_custom: {}
helloworld_docker_labels: "{{ docker_labels_common
                              | combine(helloworld_docker_labels_default)
                              | combine(helloworld_docker_labels_custom) }}"

# Hostname
helloworld_docker_hostname: "{{ helloworld_name }}"

# Networks
helloworld_docker_networks_alias: "{{ helloworld_name }}"
helloworld_docker_networks_default: []
helloworld_docker_networks_custom: []
helloworld_docker_networks: "{{ docker_networks_common
                                + helloworld_docker_networks_default
                                + helloworld_docker_networks_custom }}"

# Capabilities
helloworld_docker_capabilities_default: []
helloworld_docker_capabilities_custom: []
helloworld_docker_capabilities: "{{ helloworld_docker_capabilities_default
                                    + helloworld_docker_capabilities_custom }}"

# Security Opts
helloworld_docker_security_opts_default: []
helloworld_docker_security_opts_custom: []
helloworld_docker_security_opts: "{{ helloworld_docker_security_opts_default
                                     + helloworld_docker_security_opts_custom }}"

# Restart Policy
helloworld_docker_restart_policy: unless-stopped

# State
helloworld_docker_state: started
